# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ml_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_service.proto\x12\x02ml\"\x1f\n\x0ePredictRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"Q\n\x0fPredictResponse\x12\x17\n\x0ftalc_percentage\x18\x01 \x01(\x02\x12\x13\n\x0boverlay_png\x18\x02 \x01(\x0c\x12\x10\n\x08mask_png\x18\x03 \x01(\x0c\x32?\n\tMLService\x12\x32\n\x07Predict\x12\x12.ml.PredictRequest\x1a\x13.ml.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=24
  _globals['_PREDICTREQUEST']._serialized_end=55
  _globals['_PREDICTRESPONSE']._serialized_start=57
  _globals['_PREDICTRESPONSE']._serialized_end=138
  _globals['_MLSERVICE']._serialized_start=140
  _globals['_MLSERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
