# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ml_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_service.proto\x12\x02ml\"A\n\x0ePredictRequest\x12\x0e\n\x06tensor\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\"\x97\x01\n\x0fPredictResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x31\n\x07metrics\x18\x03 \x03(\x0b\x32 .ml.PredictResponse.MetricsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32?\n\tMLService\x12\x32\n\x07Predict\x12\x12.ml.PredictRequest\x1a\x13.ml.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTRESPONSE_METRICSENTRY']._loaded_options = None
  _globals['_PREDICTRESPONSE_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_PREDICTREQUEST']._serialized_start=24
  _globals['_PREDICTREQUEST']._serialized_end=89
  _globals['_PREDICTRESPONSE']._serialized_start=92
  _globals['_PREDICTRESPONSE']._serialized_end=243
  _globals['_PREDICTRESPONSE_METRICSENTRY']._serialized_start=197
  _globals['_PREDICTRESPONSE_METRICSENTRY']._serialized_end=243
  _globals['_MLSERVICE']._serialized_start=245
  _globals['_MLSERVICE']._serialized_end=308
# @@protoc_insertion_point(module_scope)
